-- Test verilerini ekleme scripti
-- Oracle SQL Developer ile çalıştırılacak

-- VAKIF Hastanesi test verileri
INSERT INTO VAKIF_HASTALAR (AD, SOYAD, DOGUM_TARIHI) VALUES ('Ahmet', 'Yılmaz', TO_DATE('1985-03-15', 'YYYY-MM-DD'));
INSERT INTO VAKIF_HASTALAR (AD, SOYAD, DOGUM_TARIHI) VALUES ('Fatma', 'Demir', TO_DATE('1990-07-22', 'YYYY-MM-DD'));
INSERT INTO VAKIF_HASTALAR (AD, SOYAD, DOGUM_TARIHI) VALUES ('Mehmet', 'Kaya', TO_DATE('1978-11-08', 'YYYY-MM-DD'));
INSERT INTO VAKIF_HASTALAR (AD, SOYAD, DOGUM_TARIHI) VALUES ('Ayşe', 'Özkan', TO_DATE('1992-05-14', 'YYYY-MM-DD'));
INSERT INTO VAKIF_HASTALAR (AD, SOYAD, DOGUM_TARIHI) VALUES ('Ali', 'Çelik', TO_DATE('1987-09-30', 'YYYY-MM-DD'));

-- DEVLET Hastanesi test verileri
INSERT INTO DEVLET_HASTALAR (ISIM, SOYISIM, DOGUMYILI) VALUES ('Zeynep', 'Arslan', '1983');
INSERT INTO DEVLET_HASTALAR (ISIM, SOYISIM, DOGUMYILI) VALUES ('Mustafa', 'Şahin', '1991');
INSERT INTO DEVLET_HASTALAR (ISIM, SOYISIM, DOGUMYILI) VALUES ('Elif', 'Türk', '1989');
INSERT INTO DEVLET_HASTALAR (ISIM, SOYISIM, DOGUMYILI) VALUES ('Hasan', 'Güneş', '1975');
INSERT INTO DEVLET_HASTALAR (ISIM, SOYISIM, DOGUMYILI) VALUES ('Selin', 'Koç', '1994');

-- Değişiklikleri kaydet
COMMIT;

-- Veri kontrolü
SELECT 'VAKIF HASTALAR' AS TABLO, COUNT(*) AS KAYIT_SAYISI FROM VAKIF_HASTALAR
UNION ALL
SELECT 'DEVLET HASTALAR' AS TABLO, COUNT(*) AS KAYIT_SAYISI FROM DEVLET_HASTALAR;










