-- LocalDB Kurulum Scripti
-- SQL Server Management Studio veya Visual Studio'da çalıştırın

-- 1. VAKIF Hastanesi için veritabanı ve tablo
CREATE DATABASE VAKIF_DB;
GO

USE VAKIF_DB;
GO

CREATE TABLE VAKIF_HASTALAR (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    AD NVARCHAR(50) NOT NULL,
    SOYAD NVARCHAR(50) NOT NULL,
    DOGUM_TARIHI DATE NOT NULL,
    KAYIT_TARIHI DATETIME DEFAULT GETDATE()
);

-- Test verileri
INSERT INTO VAKIF_HASTALAR (AD, SOYAD, DOGUM_TARIHI) VALUES 
('Ahmet', 'Yılmaz', '1985-03-15'),
('Fatma', 'Demir', '1990-07-22'),
('Mehmet', 'Kaya', '1978-11-08'),
('Ayşe', 'Özkan', '1992-05-14'),
('Ali', 'Çelik', '1987-09-30');

-- 2. DEVLET Hastanesi için veritabanı ve tablo
CREATE DATABASE DEVLET_DB;
GO

USE DEVLET_DB;
GO

CREATE TABLE DEVLET_HASTALAR (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ISIM NVARCHAR(50) NOT NULL,
    SOYISIM NVARCHAR(50) NOT NULL,
    DOGUMYILI NVARCHAR(10) NOT NULL,
    KAYIT_TARIHI DATETIME DEFAULT GETDATE()
);

-- Test verileri
INSERT INTO DEVLET_HASTALAR (ISIM, SOYISIM, DOGUMYILI) VALUES 
('Zeynep', 'Arslan', '1983'),
('Mustafa', 'Şahin', '1991'),
('Elif', 'Türk', '1989'),
('Hasan', 'Güneş', '1975'),
('Selin', 'Koç', '1994');

-- 3. MASTER Veritabanı
CREATE DATABASE MASTER_DB;
GO

USE MASTER_DB;
GO

CREATE TABLE MASTER_HASTALAR (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    AD NVARCHAR(50) NOT NULL,
    SOYAD NVARCHAR(50) NOT NULL,
    DOGUM_TARIHI DATE NOT NULL,
    HASTANE_NO INT NOT NULL,
    KAYIT_TARIHI DATETIME DEFAULT GETDATE(),
    KAYNAK_HASTANE NVARCHAR(50)
);

-- Veri kontrolü
SELECT 'VAKIF HASTALAR' AS TABLO, COUNT(*) AS KAYIT_SAYISI FROM VAKIF_DB.dbo.VAKIF_HASTALAR
UNION ALL
SELECT 'DEVLET HASTALAR' AS TABLO, COUNT(*) AS KAYIT_SAYISI FROM DEVLET_DB.dbo.DEVLET_HASTALAR;

-- LocalDB bağlantı testi
SELECT 'LocalDB Bağlantısı Başarılı!' AS DURUM;











